name: Unit Tests

on:
  pull_request:

jobs:
  unit-tests:
    name: Run testDebugUnitTest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run testDebugUnitTest
        run: ./gradlew testDebugUnitTest
