name: Unit Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  unit-tests:
    name: Run all module unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests in all modules with detailed logs
        run: |
          ./gradlew :app:testDebugUnitTest \
                    :data:testDebugUnitTest \
                    :domain:testDebugUnitTest \
                    --no-parallel --info --stacktrace

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: all-test-reports
          path: |
            app/build/reports/tests/testDebugUnitTest
            data/build/reports/tests/testDebugUnitTest
            domain/build/reports/tests/testDebugUnitTest
