name: Unit Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Run all unit tests with visible output
        run: |
          ./gradlew \
            :app:testDebugUnitTest \
            :data:testDebugUnitTest \
            :domain:testDebugUnitTest \
            --info --stacktrace --console=plain \
            --tests "*"

      - name: Upload test report HTMLs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            app/build/reports/tests/testDebugUnitTest
            data/build/reports/tests/testDebugUnitTest
            domain/build/reports/tests/testDebugUnitTest
