- name: Run unit tests with detailed output
  run: |
    ./gradlew \
      :app:testDebugUnitTest \
      :data:testDebugUnitTest \
      :domain:testDebugUnitTest \
      --info --stacktrace --console=plain

- name: Upload test results for PR comment
  uses: dorny/test-reporter@v1
  if: always()
  with:
    name: Unit Tests
    path: '**/build/test-results/testDebugUnitTest/*.xml'
    reporter: java-junit
    fail-on-error: false
